// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace GooglePlayGames.ConstantsClass
{
public static class GPGSConstants
{
        public const string achievement_black_hole_escaper_i = "CgkI85jcudQLEAIQFw"; // <GPGSID>
        public const string achievement_expert_collector = "CgkI85jcudQLEAIQHw"; // <GPGSID>
        public const string achievement_monster_rider_ii = "CgkI85jcudQLEAIQFQ"; // <GPGSID>
        public const string achievement_black_hole_escaper_ii = "CgkI85jcudQLEAIQGA"; // <GPGSID>
        public const string event_overall_collected_cubes = "CgkI85jcudQLEAIQCQ"; // <GPGSID>
        public const string leaderboard_cube_collecter_ranking = "CgkI85jcudQLEAIQCA"; // <GPGSID>
        public const string quest___2_ = "CgkI85jcudQLEAIQCg"; // <GPGSID>
        public const string achievement_meteor_smasher_ii = "CgkI85jcudQLEAIQGw"; // <GPGSID>
        public const string BUNDLE_ID = "com.morogoro.shoong"; // <GPGSID>
        public const string achievement_monster_rider_iii = "CgkI85jcudQLEAIQFg"; // <GPGSID>
        public const string achievement_cube_collector_ii = "CgkI85jcudQLEAIQEg"; // <GPGSID>
        public const string achievement_cube_collector_i = "CgkI85jcudQLEAIQEQ"; // <GPGSID>
        public const string achievement_monster_rider_i = "CgkI85jcudQLEAIQFA"; // <GPGSID>
        public const string achievement_meteor_smasher_iii = "CgkI85jcudQLEAIQHA"; // <GPGSID>
        public const string achievement_cube_collector_iii = "CgkI85jcudQLEAIQEw"; // <GPGSID>
        public const string achievement_novice_collector = "CgkI85jcudQLEAIQHQ"; // <GPGSID>
        public const string achievement_intermediate_collector = "CgkI85jcudQLEAIQHg"; // <GPGSID>
        public const string achievement_black_hole_escaper_iii = "CgkI85jcudQLEAIQGQ"; // <GPGSID>
        public const string achievement_meteor_smasher_i = "CgkI85jcudQLEAIQGg"; // <GPGSID>

}
}
