// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSConstants
{
        public const string achievement_fine_dreamwalker = "CgkIubjEkcMWEAIQAw"; // <GPGSID>
        public const string leaderboard_highest_overall_points = "CgkIubjEkcMWEAIQDg"; // <GPGSID>
        public const string achievement_novice_toy_collector = "CgkIubjEkcMWEAIQBA"; // <GPGSID>
        public const string achievement_persistent_traveler = "CgkIubjEkcMWEAIQDA"; // <GPGSID>
        public const string achievement_fantastic_dreamwalker = "CgkIubjEkcMWEAIQCA"; // <GPGSID>
        public const string achievement_intermediate_toy_collector = "CgkIubjEkcMWEAIQCQ"; // <GPGSID>
        public const string achievement_steady_traveler = "CgkIubjEkcMWEAIQCw"; // <GPGSID>
        public const string achievement_excellent_dreamwalker = "CgkIubjEkcMWEAIQBw"; // <GPGSID>
        public const string achievement_master_toy_collector = "CgkIubjEkcMWEAIQCg"; // <GPGSID>
        public const string achievement_endless_traveler = "CgkIubjEkcMWEAIQDQ"; // <GPGSID>
        public const string leaderboard_highest_points = "CgkIubjEkcMWEAIQBg"; // <GPGSID>

}

